In [1]:
import numpy as np

In [2]:
np.array([0] * 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones([2,2], dtype=np.int)

C:\Users\German\AppData\Local\Temp/ipykernel_6132/2225746612.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

In [5]:
np.ones([3,2], dtype=np.float)

C:\Users\German\AppData\Local\Temp/ipykernel_6132/2134205708.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
X = np.arange(4, dtype=np.int)

C:\Users\German\AppData\Local\Temp/ipykernel_6132/3735957674.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype=np.int)


In [7]:
np.ones_like(X)

array([1, 1, 1, 1])

In [8]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

C:\Users\German\AppData\Local\Temp/ipykernel_6132/3323365507.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1,2,3], [4,5,6]], dtype=np.int)


In [9]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.ones([4,4], dtype=np.int) * 5

C:\Users\German\AppData\Local\Temp/ipykernel_6132/3878826747.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.randint(10, size=3)

array([4, 1, 8])

In [16]:
np.random.random((3,3,3)) 

array([[[0.32961319, 0.80969493, 0.98315825],
        [0.79057636, 0.1212061 , 0.30144921],
        [0.89297069, 0.37278034, 0.12661714]],

       [[0.63202002, 0.2873978 , 0.79651551],
        [0.96755981, 0.14231796, 0.96704659],
        [0.56356418, 0.41211517, 0.59709228]],

       [[0.19330201, 0.43101144, 0.72649256],
        [0.6028912 , 0.48417588, 0.02303024],
        [0.73662227, 0.18694662, 0.55368415]]])

In [17]:
np.random.randn(3,3,3)

array([[[-0.5752425 ,  0.02059825, -0.20462395],
        [-1.39446735, -0.86420583,  1.09243871],
        [ 0.03475867, -0.78217774, -1.29693768]],

       [[-1.44102684, -0.65828913,  0.7915955 ],
        [-2.08140084,  1.54235868, -1.05565557],
        [-2.45355648, -0.03242847, -0.52337735]],

       [[ 0.77350725, -1.81243531, -0.06693633],
        [ 1.38317588, -1.39765085, -0.6686955 ],
        [-0.24474981,  0.50529723,  0.16483763]]])

In [18]:
X = [1, 2, 3]

In [19]:
X

[1, 2, 3]

In [20]:
type(X)

list

In [21]:
Y = np.array(X)

In [22]:
Y

array([1, 2, 3])

In [23]:
type(Y)

numpy.ndarray

In [24]:
X = np.array([5,2,3], dtype=np.int)

C:\Users\German\AppData\Local\Temp/ipykernel_6132/2398517102.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([5,2,3], dtype=np.int)


In [25]:
X

array([5, 2, 3])

In [26]:
id(X)

106413584

In [27]:
Y = np.copy(X)

In [28]:
Y

array([5, 2, 3])

In [29]:
id(Y)

106413968

In [30]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [32]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [33]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
X = np.array(['A','B','C','D','E'])


In [35]:
X[0]

'A'

In [36]:
X = np.array(['A','B','C','D','E'])

In [37]:
X[len(X)-1]

'E'

In [38]:
X[-1]

'E'

In [39]:
X = np.array(['A','B','C','D','E'])

In [40]:
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [41]:
X = np.array(['A','B','C','D','E'])

In [42]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [43]:
X = np.array(['A','B','C','D','E'])

In [44]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [45]:
X = np.array(['A','B','C','D','E'])

In [46]:
X[[0, 2, -1]]

array(['A', 'C', 'E'], dtype='<U1')

In [47]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [48]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [49]:
X[0]

array([1, 2, 3, 4])

In [50]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [51]:
X[-1]

array([13, 14, 15, 16])

In [52]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [53]:
X[0, 0]

1

In [54]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [55]:
X[-1, -1]

16

In [56]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [57]:
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [58]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [59]:
X[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [60]:
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [61]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [62]:
X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [63]:
X = [-5, -3, 0, 10, 40]

In [64]:
np.array(X, np.float)

C:\Users\German\AppData\Local\Temp/ipykernel_6132/529530584.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

In [65]:
X = [-5, -3, 0, 10, 40]

In [66]:
X[::-1]

[40, 10, 0, -3, -5]

In [67]:
X = [0, 10, -5, 40, -3]

In [68]:
X.sort()

In [69]:
X

[-5, -3, 0, 10, 40]

In [70]:
X = np.zeros(10)

In [71]:
X[4] = 1

In [72]:
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [73]:
X = np.array([10, 20, 30, 50])

In [74]:
X[3] = 40

In [75]:
X

array([10, 20, 30, 40])

In [76]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [77]:
X[-1] = np.array([1, 1, 1, 1])

In [78]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [79]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [80]:
X[-1, -1] = 0

In [81]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [82]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [83]:
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [84]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

In [85]:
mask = X <= 0

In [86]:
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [87]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [88]:
mask = X <= 0

In [89]:
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [90]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [91]:
mask = X > 5

In [92]:
X[mask]

array([ 6, 10])

In [93]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [94]:
mask = X > X.mean()

In [95]:
X[mask]

array([ 2,  5,  6, 10])

In [96]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [97]:
mask = (X == 2) | (X == 10)

In [98]:
X[mask]


array([ 2, 10])

In [99]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [100]:
X.all()

False

In [101]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

In [102]:
X.any()

True

In [103]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

In [104]:
np.sum(X)

43

In [105]:
X.sum()

43

In [106]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

In [107]:
np.mean(X)

3.7

In [108]:
X.mean()

3.7

In [109]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [110]:
X.sum(axis=0)

array([28, 32, 36, 40])

In [111]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


In [112]:
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

In [113]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

In [114]:
np.max(X)

10

In [115]:
X.max()

10